### ISSUE TITLE
Library throws an internal error when a url with a param is provided as an Argument

### ISSUE THREAD

**Issue by CosmicOsmium** [21Joakim/Jockie-Utils#16]
When the library parses a url with a param for arguments it throws a internal error
_Version: jda-v4-SNAPSHOT_
### Screenshot of myself testing this
https://cdn.discordapp.com/attachments/588014518530080794/611116397015334923/unknown.png

### Example code
`class ExampleCommand : CommandImpl("example") {
  fun onCommand(event: CommandEvent, @Argument query: String) {
    event.channel.sendMessage(query).queue()
  }
}`

### Error thrown
`[20:37:50:305] [JDA [0 / 1] Main] [   ERROR] [             net.dv8tion.jda.api.JDA] :: One of the EventListeners had an uncaught exception 
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.jockie.bot.core.utility.StringUtility.parseWrapped(StringUtility.java:50)
	at com.jockie.bot.core.utility.StringUtility.parseWrapped(StringUtility.java:46)
	at com.jockie.bot.core.utility.StringUtility.asMap(StringUtility.java:84)
	at com.jockie.bot.core.command.parser.impl.CommandParserImpl.parse(CommandParserImpl.java:304)
	at com.jockie.bot.core.command.impl.CommandListener.parse(CommandListener.java:1406)
	at com.jockie.bot.core.command.impl.CommandListener.onEvent(CommandListener.java:1261)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:64)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:148)
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:838)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:737)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:716)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:876)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
`

### Steps to reproduce
run a command with any argument as a link with a param string, like a youtube video

**Comment by 21Joakim** [comment]
You can do `@Command(allowedArgumentParsingTypes=ArgumentParsingType.POSITIONAL)` as a temporary solution

**Comment by CosmicOsmium** [comment]
Thank you so much! I would never have found that!
